### ISSUE TITLE
[Fix]: The card Description Scrollbar will show only when content is overflow vertically

### ISSUE THREAD

**Issue by Antardas** [gabrysia694/Gym-Junkies#114]
Problem
-  It doesn't look good to show scrollbars on every card unless necessary.

  ![image](https://user-images.githubusercontent.com/62651654/235953186-8fd683ca-5489-4271-aaf6-6c18ac4a59ac.png)

**Comment by gabrysia694** [comment]
Thank you for solving this issue ❤️
