### ISSUE TITLE
Updated the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [gabrysia694/Gym-Junkies#119]
Hey! I came across this repository but found the README to be a bit messy
Made the following changes : 

+ Restructured the H1
+ Reformatted the getting started section
+ Added badges for a cool look
+ Added styling like bold etc

**Comment by gabrysia694** [comment]
Hey @the-amazing-atharva, I'd love to see the changes you've made. Could you create a pull request?

**Comment by suzy-g38** [comment]
Hey, @the-amazing-atharva can I work with you on the one?

**Comment by the-amazing-atharva** [comment]
> Hey @the-amazing-atharva, I'd love to see the changes you've made. Could you create a pull request?

I am not able to make a PR, getting some actions error could you check the authorization or have I made some error?

**Comment by the-amazing-atharva** [comment]
> Hey @the-amazing-atharva, I'd love to see the changes you've made. Could you create a pull request?

@gabrysia694 just linked a PR

**Comment by the-amazing-atharva** [comment]
> Hey, @the-amazing-atharva can I work with you on the one?

@suzy-g38  Saw the comment just now, I had actually made some changes yesterday night and linked a PR but I believe there are many changes to be made to the README

Let me know if you want to work on it together if my PR gets merged

Regards!

**Comment by suzy-g38** [comment]
> > Hey, @the-amazing-atharva can I work with you on the one?
> 
> @suzy-g38 Saw the comment just now, I had actually made some changes yesterday night and linked a PR but I believe there are many changes to be made to the README
> 
> Let me know if you want to work on it together if my PR gets merged
> 
> Regards!

If you think there are still things to be done after the merge, yes sure...why not. I would be happy to work together.

**Comment by the-amazing-atharva** [comment]
> > > Hey, @the-amazing-atharva can I work with you on the one?
> > 
> > 
> > @suzy-g38 Saw the comment just now, I had actually made some changes yesterday night and linked a PR but I believe there are many changes to be made to the README
> > Let me know if you want to work on it together if my PR gets merged
> > Regards!
> 
> If you think there are still things to be done after the merge, yes sure...why not. I would be happy to work together.

Will let you know :)

**Comment by suzy-g38** [comment]
> > > > Hey, @the-amazing-atharva can I work with you on the one?
> > > 
> > > 
> > > @suzy-g38 Saw the comment just now, I had actually made some changes yesterday night and linked a PR but I believe there are many changes to be made to the README
> > > Let me know if you want to work on it together if my PR gets merged
> > > Regards!
> > 
> > 
> > If you think there are still things to be done after the merge, yes sure...why not. I would be happy to work together.
> 
> Will let you know :)

Sure

**Comment by gabrysia694** [comment]
hey @suzy-g38! @the-amazing-atharva did a great job with updating our README.md but one of our contributors created issue #120, would you like to work on that? :)

**Comment by suzy-g38** [comment]
> hey @suzy-g38! @the-amazing-atharva did a great job with updating our README.md but one of our contributors created issue #120, would you like to work on that? :)

Ofc I would love to but #120 is closed.
