### ISSUE TITLE
[DOCS] Add Contributing Guidelines

### ISSUE THREAD

**Issue by KendallDoesCoding** [gabrysia694/Gym-Junkies#12]

**Comment by harisdev-netizen** [comment]
Can you assign me this issue?

**Comment by gabrysia694** [comment]
> Can you assign me this issue?

sure! you're assigned now.

**Comment by harisdev-netizen** [comment]
Hey there @gabrysia694 quick question. Should I create a new file for Contributing Guidelines or just add it to the README.md?

**Comment by gabrysia694** [comment]
> Hey there @gabrysia694 quick question. Should I create a new file for Contributing Guidelines or just add it to the README.md?

I think it'd be best to create a new file for Contributing and just move Template and instruction from README.md to that newly created file :)

**Comment by harisdev-netizen** [comment]
You got it.
