### ISSUE TITLE
Add Space between Cards

### ISSUE THREAD

**Issue by suzy-g38** [gabrysia694/Gym-Junkies#123]
On the guide page, there is no space between the two cards. If there is space, it will enhance the design.

![image](https://user-images.githubusercontent.com/62666287/236389950-66a23fe0-dc98-404f-8cde-81a263f902c2.png)

**Comment by adityadafe** [comment]
@suzy-g38 ive checked i think there is enough space between cards,
 might be bug from your side.

**Comment by suzy-g38** [comment]
> @suzy-g38 ive checked i think there is enough space between cards, might be bug from your side.

I actually tried the url provided in the github: https://gymjunkies.netlify.app/

**Comment by suzy-g38** [comment]
> @suzy-g38 ive checked i think there is enough space between cards, might be bug from your side.

I found the reason. Actually you are using maybe a big screen....that's why there is no spacing issue. But if you use a smaller screen you will find there is no space in between cards.

**Comment by adityadafe** [comment]
i tried changing the dimension looks like media queries are well written and work perfectly maybe  changing browser might solve the issue.

**Comment by priyankarpal** [comment]
yeah i found the same issue @suzy-g38 we need to add `gap` between cards

**Comment by gabrysia694** [comment]
adding some space between cards sounds like a good idea, would you like to work on that @suzy-g38?

**Comment by suzy-g38** [comment]
Yeah sure

**Comment by gabrysia694** [comment]
> Yeah sure

awesome, i'll assign you right away
