### ISSUE TITLE
remove the label

### ISSUE THREAD

**Issue by priyankarpal** [gabrysia694/Gym-Junkies#128]
we need to remove the label & add some extra label like `style`

![image](https://user-images.githubusercontent.com/88102392/236551124-468cb80a-742f-4583-8ec3-aaa709b854a5.png)

**Comment by gabrysia694** [comment]
remove the good-first-issue on #3? why?

**Comment by priyankarpal** [comment]
> remove the good-first-issue on #3? why?

it's showing another community name. `eddiehub` remove only `eddiehub`

**Comment by gabrysia694** [comment]
> > remove the good-first-issue on #3? why?
> 
> it's showing another community name. `eddiehub` remove only `eddiehub`

oh I saw that they had a good app for open-source projects and I thought that using the label on our app to get it on the list wouldn't be an issue
