### ISSUE TITLE
[style]: adding bullet points

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/Gym-Junkies#159]
Adding bullet points to each step of the exercise instructions would enhance readability.

**Comment by Helixjoe** [comment]
Can I work on this ?

**Comment by gabrysia694** [comment]
> Can I work on this ?

all yours

**Comment by Helixjoe** [comment]
Made the PR #162 , kindly review it

**Comment by gabrysia694** [comment]
> Made the PR #162 , kindly review it

I requested a small change, could you take a look at it?
