### ISSUE TITLE
[Bug]: Squats Image

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [gabrysia694/Gym-Junkies#170]
### What happened?

I have noticed an issue with the image associated with the squats. Upon attempting to access the source URL of the image, it consistently displays a server error. This error has persisted for the past four days. To provide a visual reference, I have attached a screenshot for your convenience.

### Add screenshots

![Screenshot (85)](https://github.com/gabrysia694/Gym-Junkies/assets/112751524/621e9f3b-1aea-45e7-ada1-2402df6369b3)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CedricNdong** [comment]
> ### What happened?
> I have noticed an issue with the image associated with the squats. Upon attempting to access the source URL of the image, it consistently displays a server error. This error has persisted for the past four days. To provide a visual reference, I have attached a screenshot for your convenience.
> 
> ### Add screenshots
> ![Screenshot (85)](https://user-images.githubusercontent.com/112751524/243065093-621e9f3b-1aea-45e7-ada1-2402df6369b3.png)
> 
> ### What browsers are you seeing the problem on?
> Microsoft Edge
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Google Chrome

**Comment by CedricNdong** [comment]
Can you assign this bug to me please?
