### ISSUE TITLE
Adding link to github repository for contribution

### ISSUE THREAD

**Issue by lipwei1808** [gabrysia694/Gym-Junkies#174]
At the bottom of the page there is a CTA to users to contribute. However, no link is provided.

I propose to add a link for better UX.

<img width="937" alt="Screenshot 2023-06-07 145549" src="https://github.com/gabrysia694/Gym-Junkies/assets/53000252/bfcd8703-1d70-4401-bd48-6b5a62698728">

**Comment by gabrysia694** [comment]
Great idea, would you like to work on that?
