### ISSUE TITLE
[style]: Centering of images on smaller devices

### ISSUE THREAD

**Issue by shobhitexe** [gabrysia694/Gym-Junkies#182]
### What's the style idea?

On Small devices the image is not centered as we can see on below SS i guess it will look much better if centered 

### Add screenshots

![image](https://github.com/gabrysia694/Gym-Junkies/assets/29349136/7f24d00d-372f-4e2b-afbb-98a9b3a1801e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabrysia694** [comment]
Good idea, would you like to work on that?

**Comment by shobhitexe** [comment]
> Good idea, would you like to work on that?

Yes sure 👍
