### ISSUE TITLE
[style]: Centering the Navbar

### ISSUE THREAD

**Issue by gabrysia694** [gabrysia694/Gym-Junkies#183]
### What's the style idea?

We could align the Navbar at the center for smaller devices to improve the appearance

### Add screenshots

![353886220_777388980541686_7828538849634024457_n](https://github.com/gabrysia694/Gym-Junkies/assets/97764356/554de60b-7df6-4eea-bef0-ac313787d4b3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thedipayanb** [comment]
Hey @gabrysia694 Can I please work on this issue?

**Comment by thedipayanb** [comment]
Hey @gabrysia694 I made a PR(#185), which fix this issue. Can you please review it? Thank you.
