### ISSUE TITLE
[style]: improving dark mode

### ISSUE THREAD

**Issue by shobhitexe** [gabrysia694/Gym-Junkies#191]
### What's the style idea?

As we can see on attached SS the cards on Schedule and contributors will look more good if we give them colors like this on dark mode instead of white which is looking bit odd and not matching with overall styling 

### Add screenshots

![image](https://github.com/gabrysia694/Gym-Junkies/assets/29349136/445d2de7-c640-4695-9d94-7a1e2024995e)

![image](https://github.com/gabrysia694/Gym-Junkies/assets/29349136/63cbbf5f-fa87-41ad-a954-b9292728ae64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabrysia694** [comment]
Thank you for raising this issue, it has just been updated. Could you take a look at the website and eventually suggest any additional changes?

**Comment by shobhitexe** [comment]
> Thank you for raising this issue, it has just been updated. Could you take a look at the website and eventually suggest any additional changes?

Ahhh np , yes sure ill create a issue whenever i find one
