### ISSUE TITLE
[style]: Updating scrollbar styles to better fit general app styles.

### ISSUE THREAD

**Issue by manuel12** [gabrysia694/Gym-Junkies#210]
### What's the style idea?

We could improve the scrollbar stylings from the current "generic" scrollbar to a scrollbar more like the current UI design of the app.

### Add screenshots

Currently the scroll bar in exercises and in the main pages look like this:

![image](https://github.com/gabrysia694/Gym-Junkies/assets/4129325/6bf39ebe-0023-4357-b074-a353f03074b9)

Instead we could have a custom scrollbar looking something like this:

![image](https://github.com/gabrysia694/Gym-Junkies/assets/4129325/15458fca-b4b3-4969-9476-5394f24271bd)

Please assign me this ticket and I will make a PR :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabrysia694** [comment]
Looks great @manuel12, I'll assign it to you right away :)
