### ISSUE TITLE
[style]: Add a hamburger button and menu on mobile resolutions

### ISSUE THREAD

**Issue by manuel12** [gabrysia694/Gym-Junkies#211]
### What's the style idea?

We could add a hamburger menu for mobile resolutions this way the current navbar elements would not appear all crammed together.

### Add screenshots

The navbar looks like this on mobile resolutions currently:

![image](https://github.com/gabrysia694/Gym-Junkies/assets/4129325/d389d35f-d147-4aa0-9f7f-31f880c20442)

I could make it look something like this:

![image](https://github.com/gabrysia694/Gym-Junkies/assets/4129325/1bce3f4e-7ac8-478c-9550-b12fb35276d9)

Please assign this to me if you agree with the changes :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabrysia694** [comment]
Great, all yours :)
