### ISSUE TITLE
[Feat]:  Customization of Scrollbar Style

### ISSUE THREAD

**Issue by Saurav-Pant** [gabrysia694/Gym-Junkies#213]
### What feature?

I suggest incorporating a custom scroll bar on the website to enhance its visual appeal and improve user experience. If you think this would be beneficial, please assign this task to me. Kindly specify the preferred color or any specific design requirements for the scroll bar.

### Add screenshots

currently, it is 
![scrollbar_current](https://github.com/gabrysia694/Gym-Junkies/assets/103263909/aad4a29b-a026-437e-81df-09f497807b59)
but we can make like this 
![scrollbar_change](https://github.com/gabrysia694/Gym-Junkies/assets/103263909/86e1fa45-760f-46d8-bea8-0dfb6f129a18)

if you think it is a good idea tell me which color perfectly aligns with it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gabrysia694** [comment]
Thank you @Saurav-Pant for raising this issue but it has just been fixed. If you have any other suggestions, I'd love to hear them!
