### ISSUE TITLE
navbar logo is not correct

### ISSUE THREAD

**Issue by vijaykanwal90** [gabrysia694/Gym-Junkies#225]
### What's the style idea?

We need to improve  

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Chavda-Mitul** [comment]
i can fix this

**Comment by Chavda-Mitul** [comment]
hey the sun should also be in the ends or i just need to fix the logo?

**Comment by Chavda-Mitul** [comment]
1 
![Screenshot from 2023-07-15 11-05-34](https://github.com/gabrysia694/Gym-Junkies/assets/82195661/70d297cc-23c8-481b-8c31-ae8f982eef9a)
2 
![Screenshot from 2023-07-15 11-05-08](https://github.com/gabrysia694/Gym-Junkies/assets/82195661/95fadca7-a070-430e-bcd8-887a5a457e88)

which one is better?
