### ISSUE TITLE
The Add your favorite exercise Button

### ISSUE THREAD

**Issue by Akbar-Ahmed** [gabrysia694/Gym-Junkies#23]
Hi , 

I think we can change the font of the Add your favorite exercise button, We can use some bright colour and bold the text as well as we can add (+) symbol after the text so it looks good to the viewer.

**Comment by gabrysia694** [comment]
Hello,
that's a great suggestion. Would you like to work on that?

**Comment by Akbar-Ahmed** [comment]
I need to look onto that !  Will update  you soon
