### ISSUE TITLE
Update Read me 

### ISSUE THREAD

**Issue by Akbar-Ahmed** [gabrysia694/Gym-Junkies#24]
Hey,  If someone is looking at the repository, the first thing he sees is Read me.
You can add the website URL in Read me file at the top so that they can check the website.  

![image](https://user-images.githubusercontent.com/70852077/231850235-040bc820-e2f3-48aa-847b-a0d81e9f7a04.png)

**Comment by gabrysia694** [comment]
Hey! Great idea, would you like to do that?

**Comment by Akbar-Ahmed** [comment]
Sure ,  I have created a PR for that.
