### ISSUE TITLE
Exercise Movement Videos

### ISSUE THREAD

**Issue by Aditya-Naresh** [gabrysia694/Gym-Junkies#32]
Would you like add Youtube video links to each exercise? or add a feature for it to pop out and play on the page itself? @gabrysia694 .

**Comment by gabrysia694** [comment]
> Would you like add Youtube video links to each exercise? or add a feature for it to pop out and play on the page itself? @gabrysia694 .

There are video links already added but a feature which makes a video pop out after clicking on the exercise would be cool. Would you like to work on that?

**Comment by Aditya-Naresh** [comment]
Yes, I'd like to work on that.

**Comment by gabrysia694** [comment]
> Yes, I'd like to work on that.

Awesome, it's all yours then

**Comment by Aditya-Naresh** [comment]
![image](https://user-images.githubusercontent.com/64772267/232978106-2c233ad0-96b3-4ec2-9049-63addf11161e.png)

@gabrysia694 I have found a way to implement this feature but it slightly changes the template code as well . I think it's better if I update the template first , so that those who will contribute will automatically have this feature implemented on their card and I'll implement it one by one on the exercise contributions.
