### ISSUE TITLE
Improvement in hover State

### ISSUE THREAD

**Issue by rahulrana701** [gabrysia694/Gym-Junkies#37]
if we make the color of the text white when someone hover on these cards, it will improve the readability and it looks better as well...
<img width="290" alt="Screenshot 2023-04-19 014034" src="https://user-images.githubusercontent.com/123585591/232894490-60b649f1-a60c-481a-9736-2335d7c1504e.png">

**Comment by rahulrana701** [comment]
hi @gabrysia694 if you want I would like to work on this issue..

**Comment by Lalman888** [comment]
@gabrysia694  Can I work on this issue

**Comment by rahulrana701** [comment]
hi @gabrysia694 I have created a pr regarding this issue......https://github.com/gabrysia694/Gym-Junkies/pull/39#issue-1674473430

**Comment by Lalman888** [comment]
![image](https://user-images.githubusercontent.com/90516185/233024325-d22c0bc0-c50d-4534-9282-48ec533fc305.png)
if link tag color also become white then it will look good

**Comment by rahulrana701** [comment]
hi @Lalman888 the link tag is also getting white when someone hover on it.......
If we make the anchor tag white in without hover state it will not look good....

**Comment by gabrysia694** [comment]
hey @Lalman888, we could also change the color on hover for icons in the footer. Would you like to work on that?

**Comment by rahulrana701** [comment]
hi @gabrysia694 I can work on this right now if  you want , just tell me what type of effect you want on hover..

**Comment by Lalman888** [comment]
let @RahulRana701  work on this icons issue

**Comment by Lalman888** [comment]
@gabrysia694  Can we add YouTube videoplayer on home instead of redirecting the user to another link

**Comment by gabrysia694** [comment]
> hi @gabrysia694 I can work on this right now if you want , just tell me what type of effect you want on hover..

just a change of color, could be one of the colors already present on the page so it matches the overall theme

**Comment by gabrysia694** [comment]
> @gabrysia694 Can we add YouTube videoplayer on home instead of redirecting the user to another link

one of the contributors is already working on it so this feature should be added soon

**Comment by Lalman888** [comment]
@gabrysia694  there is one suggestion we can make added by contributer page contributer as a card  and 
add your favorite page will be good 
Can we just transfer this code to nextjs it will be good and code will be more structured?

**Comment by gabrysia694** [comment]
> @gabrysia694 there is one suggestion we can make added by contributer page contributer as a card and add your favorite page will be good Can we just transfer this code to nextjs it will be good and code will be more structured?

I'm not sure if I understood correctly, do you want to make a card with a list of contributors and their favourite pages?

**Comment by Lalman888** [comment]
can we make this ?

**Comment by gabrysia694** [comment]
> can we make this ?

we can! you can create a new button next to "Add your favourite exercise (+)" which will open a new page with a list of contributors or show a card with a list or like a drop down menu but with a list. I'll let you decide what looks best!

**Comment by Lalman888** [comment]
Can we switch to nextjs ?

**Comment by rahulrana701** [comment]
hi @gabrysia694 I have created a pr regarding the icons hover state you can check it out https://github.com/gabrysia694/Gym-Junkies/pull/45#issue-1675527390
