### ISSUE TITLE
feat: migrate to ReactJs & Tailwind CSS

### ISSUE THREAD

**Issue by priyankarpal** [gabrysia694/Gym-Junkies#40]
Hey Maintainers, we can migrate to ReactJs & Tailwind CSS. It will help us to develop a good project. 

### HTML code getting too lengthy & it will create confusion in future for contributors. 

![Screenshot from 2023-04-19 21-08-07](https://user-images.githubusercontent.com/88102392/233128699-20a48983-d39e-4231-ae0b-fe898ebc6378.png)

### Features of the projects will be:
- we will use the JSON format to collect data
- We don't need to add lots of HTML code to display cards

### Demo of the JSON code

```
 {
  "title": "Add title ",
  "link": "YouTube Link",
  "descriptions": [
      "This is the first description",
      "This is the second description",
      "This is the third description"
    ],
  "gh-username": "Add your gh username" 
  }
``` 

> Note we will collect json code from contributors. 

### I want to work on this new feature.

**Comment by gabrysia694** [comment]
hey @priyankarpal, awesome idea! I'll assign it to you right away, take your time :)

**Comment by Lalman888** [comment]
@priyankarpal  are you using nextjs typescript ?

**Comment by priyankarpal** [comment]
> @priyankarpal are you using nextjs typescript ?

no no ReactJs & Tailwind CSS

**Comment by Lalman888** [comment]
Means vite I think using @nextjs with typescript
will make this website more optimise and error fixing will be easy

**Comment by priyankarpal** [comment]
> Means vite I think using @nextjs with typescript will make this website more optimise and error fixing will be easy

yeah, we can do it too. But my work almost completed 80%. 
and I don't have knowledge of Typescript but also I know basics of NextJs(currently learning)

**Comment by Lalman888** [comment]
Then complete this I can export this to nextjs typescript only few changes will be required. I don't suggest react because of routing and seo will be good in nextjs.

**Comment by priyankarpal** [comment]
> Then complete this I can export this to nextjs typescript only few changes will be required. I don't suggest react because of routing and seo will be good in nextjs.

yes, agree with you.

**Comment by Lalman888** [comment]
Can you try to set up nextjs with typescript?

**Comment by priyankarpal** [comment]
completed
