### ISSUE TITLE
feat: a list of contributors

### ISSUE THREAD

**Issue by Lalman888** [gabrysia694/Gym-Junkies#44]
making a list of contributors page

**Comment by priyankarpal** [comment]
> making a list of contributors page

I want to work on this issue if you don't want to work.

**Comment by Lalman888** [comment]
@gabrysia694  assign this issue to me

**Comment by gabrysia694** [comment]
> @gabrysia694 assign this issue to me

okay, here you go

**Comment by Lalman888** [comment]
@gabrysia694 what details should I add here 

![image](https://user-images.githubusercontent.com/90516185/235739694-605d263f-989a-443c-8612-ff0af5d404bf.png)

**Comment by priyankarpal** [comment]
> @gabrysia694 what details should I add here
> 
> ![image](https://user-images.githubusercontent.com/90516185/235739694-605d263f-989a-443c-8612-ff0af5d404bf.png)

you can show their names, avatars, & github link

**Comment by Lalman888** [comment]
that's done

**Comment by gabrysia694** [comment]
> @gabrysia694 what details should I add here
> 
> ![image](https://user-images.githubusercontent.com/90516185/235739694-605d263f-989a-443c-8612-ff0af5d404bf.png)

I think what you have here is enough: avatar, name and username with github link

**Comment by Lalman888** [comment]
@gabrysia694  can you review my pull request
