### ISSUE TITLE
suggest: use vercel 

### ISSUE THREAD

**Issue by priyankarpal** [gabrysia694/Gym-Junkies#47]
- we are using Netlify, it's safe but in future we will use NextJs so if we use vercel then it will help a lot 
- I will suggest use vercel

**Comment by gabrysia694** [comment]
I had no idea vercel might be better but I'll move our website there if that's what you're suggesting :smile:

**Comment by priyankarpal** [comment]
currently, it's working fine on Netlify. we don't need to switch to vercel so I'm closing this issue.
