### ISSUE TITLE
For Updating Footer

### ISSUE THREAD

**Issue by Saurav-Pant** [gabrysia694/Gym-Junkies#49]
Here Background color and color both are white so the text is invisible.
(https://user-images.githubusercontent.com/103263909/233396161-d00ffd23-bc63-483e-a7a0-30784719180e.png)
this text is invisible
(https://user-images.githubusercontent.com/103263909/233396221-1a1eaaaa-d10b-4c95-b7dd-574efc60a276.png)

**Comment by priyankarpal** [comment]
wow. but showing on my device 😢 
![image](https://user-images.githubusercontent.com/88102392/233403766-8033a933-128c-4557-8943-e05ee4d48e63.png)

**Comment by Saurav-Pant** [comment]
On my phone, it is also showing but on my laptop, it's not.

**Comment by priyankarpal** [comment]
> On my phone, it is also showing but on my laptop, it's not.

yes. I understand just enable dark mode on the laptop.

**Comment by Saurav-Pant** [comment]
oh, it means in the dark mode it is showing this, how to prevent this?

**Comment by priyankarpal** [comment]
> oh, it means in the dark mode it is showing this, how to prevent this?

this is the final code 
```
import React from "react";
import { FaGithub } from "react-icons/fa";

export default function Footer() {
  return (
    <footer aria-label="Site Footer" className="bg-gray-900">
      <div className="max-w-screen-xl px-4 pt-16 pb-8 mx-auto sm:px-6 lg:px-8 lg:pt-24">
        <div className="text-center">
          <h2 className="text-3xl font-extrabold text-white sm:text-5xl">
            Proudly Open Source 🍕
          </h2>

          <p className="max-w-sm mx-auto mt-4 text-gray-400">
            Gym Junkies is an open source project. Feel free to contribute to
            the project.
          </p>
        </div>

        <div className="pt-8 mt-16 border-t flex gap-3 border-gray-800   sm:justify-between lg:mt-24">
          <a
            href="https://github.com/gabrysia694/Gym-Junkies/blob/main/LICENSE"
            target="_blank"
            className="text-white"
          >
            Under MIT License
          </a>

          <a
            href="https://github.com/gabrysia694/Gym-Junkies"
            rel="noreferrer"
            target="_blank"
            className="text-gray-700 transition hover:opacity-75 dark:text-gray-200"
          >
            <FaGithub className="text-2xl" />
          </a>
        </div>
      </div>
    </footer>
  );
}
```

**Comment by priyankarpal** [comment]
I removed `dark:` from the `footer` line

**Comment by Saurav-Pant** [comment]
ok , now I  understand

**Comment by gabrysia694** [comment]
> ok , now I understand

@Saurav-Pant would you like to make the changes @priyankarpal suggested?

**Comment by Saurav-Pant** [comment]
yes, I will do it.

**Comment by Saurav-Pant** [comment]
#73, it's the PR

**Comment by gabrysia694** [comment]
awesome, thank you ❤️
