### ISSUE TITLE
Light And Dark Theme Toggler

### ISSUE THREAD

**Issue by Saurav-Pant** [gabrysia694/Gym-Junkies#60]
in the navbar, we can add a toggling functionality for a better user experience
(https://user-images.githubusercontent.com/103263909/233523107-ee4b0404-9e63-4b5d-8490-6b29e38ef5e3.png)
I want to work on it

**Comment by gabrysia694** [comment]
good idea, go ahead!

**Comment by Saurav-Pant** [comment]
#74, it is the PR @gabrysia694

**Comment by priyankarpal** [comment]
it's completed close this

**Comment by Saurav-Pant** [comment]
@priyankarpal  me?

**Comment by priyankarpal** [comment]
close this
