### ISSUE TITLE
suggest: add labels

### ISSUE THREAD

**Issue by priyankarpal** [gabrysia694/Gym-Junkies#64]
please add labels so that the user can check whether it's working or not. 

![image](https://user-images.githubusercontent.com/88102392/233640210-de675d2f-4f64-419d-bdb6-fa44e49200b3.png)

**Comment by gabrysia694** [comment]
do you mean adding labels like good-first-issue etc to the existing issues?

**Comment by priyankarpal** [comment]
> do you mean adding labels like good-first-issue etc to the existing issues?

yes
