### ISSUE TITLE
[chore]: improve image quality for images in DocsPage

### ISSUE THREAD

**Issue by at-the-vr** [gabrysia694/Gym-Junkies#70]
Images in DocsPage (`/src/pages/DocsPage.jsx`) seem bit compressed and have reduced quality in normal viewport of 1920 X 1080, and possibly can be updated.

Link referred: https://gymjunkies.netlify.app/DocsPage

System/Browser: Windows 10/ Chrome (112.0.5615.138)
Do I want to work on this Issue: No

**Comment by mshamir11** [comment]
Hi @gabrysia694 , can you assign this to me.

**Comment by mshamir11** [comment]
Raised PR #83. Please review.
