### ISSUE TITLE
Add availble exercices counter on the top of page 

### ISSUE THREAD

**Issue by benharrimohamed** [gabrysia694/Gym-Junkies#71]
Count number of availble exercices on the website and update it each time an exercice is added

**Comment by ZS041** [comment]
It seems this hasn't been assigned. I'd like to work on it if possible.

**Comment by gabrysia694** [comment]
> It seems this hasn't been assigned. I'd like to work on it if possible.

@benharrimohamed has already done that, some changes have been requested that's why it's not on the website just yet. I'll close the issue.
