### ISSUE TITLE
Theme selection not being persisted after page refresh

### ISSUE THREAD

**Issue by Saurav-Pant** [gabrysia694/Gym-Junkies#78]
When a user selects a theme on the website, it is not being persisted after the page refresh. As a result, the user needs to select the theme again every time they refresh the page.

To solve this issue, we can store the selected theme in the local storage of the user's browser. This way, when the user refreshes the page, the website can retrieve the selected theme from the local storage and apply it automatically.

Expected behavior: The website should remember the selected theme and apply it automatically after the page refresh.

**Comment by gabrysia694** [comment]
Great idea, would you like to work on that?

**Comment by Saurav-Pant** [comment]
yes, I will work on this.

> Great idea, would you like to work on that?
