### ISSUE TITLE
Navigational Cues - Keep current route highlighted

### ISSUE THREAD

**Issue by ZS041** [gabrysia694/Gym-Junkies#80]
When navigating between pages using the navigation links, they are highlighted on hover, but no change is made for the active link.

I suggest keeping track of the active route and highlighting the appropriate list item in the navbar. I'd like to work on this issue if possible.

**Comment by gabrysia694** [comment]
> When navigating between pages using the navigation links, they are highlighted on hover, but no change is made for the active link.
> 
> I suggest keeping track of the active route and highlighting the appropriate list item in the navbar. I'd like to work on this issue if possible.

sounds good, it's all yours then
