### ISSUE TITLE
Feature : Add tags to the exercise cards

### ISSUE THREAD

**Issue by mshamir11** [gabrysia694/Gym-Junkies#84]
Add tags to the cards to categorise the exercises. Say, it is a biceps, chest, abs, legs, calves, etc. And also a way to filter the exercise based on the category.

**Comment by gabrysia694** [comment]
> Add tags to the cards to categorise the exercises. Say, it is a biceps, chest, abs, legs, calves, etc. And also a way to filter the exercise based on the category.

Good idea, would you like to work on that?

**Comment by mshamir11** [comment]
Happy to pick it up. Can start mostly towards end of next week. Have some prior commitments. If any one else wants to pick it up meanwhile, feel free to do so.

**Comment by gabrysia694** [comment]
> Happy to pick it up. Can start mostly towards end of next week. Have some prior commitments. If any one else wants to pick it up meanwhile, feel free to do so.

okay, let's wait and see if anyone else would like to work on that. If not, it's all yours!

**Comment by haldaranup** [comment]
So we have to add one extra field to our DB file, say tag and filter out exercises accordingly. Is that the idea?

**Comment by ZS041** [comment]
> So we have to add one extra field to our DB file, say tag and filter out exercises accordingly. Is that the idea?

May want to just proactively start with an array of tags, rather than a single tag. Exercises can target multiple muscle groups. If you haven't already started working on it, I can get this done relatively quick, working on a very similar product tag/filter in a different project at the moment.

**Comment by haldaranup** [comment]
> > So we have to add one extra field to our DB file, say tag and filter out exercises accordingly. Is that the idea?
> 
> May want to just proactively start with an array of tags, rather than a single tag. Exercises can target multiple muscle groups. If you haven't already started working on it, I can get this done relatively quick, working on a very similar product tag/filter in a different project at the moment.

Yeah sure, go ahead!

**Comment by gabrysia694** [comment]
I'll assign it to you @ZS041 then

**Comment by ZS041** [comment]
Thanks all, should have something up today. Anyone have preferences for the sort UI? Simplest solution would be a single selection dropdown just to get the option up, and could always build off it to add option to select multiple in the future. Here is what I've got up so far. I think it fits the style of the site, let me know if you think there are any changes that can be made. 

![image](https://user-images.githubusercontent.com/80226316/234617062-640b8102-c4ce-4595-b5a9-af8d32a739b0.png)

If/when multiple select gets added in the future, a pill style display with each selected category would be nice, something like this.

![image](https://user-images.githubusercontent.com/80226316/234614247-98ec073d-61c1-4995-a353-bf415db63bc0.png)

**Comment by mshamir11** [comment]
This is good place to start with. How do you create these mocks.

**Comment by gabrysia694** [comment]
I don't think any changes are necessary at this point, it fits the site's theme perfectly

**Comment by ZS041** [comment]
> This is good place to start with. How do you create these mocks.

It's actually not a mockup, it's a browser called Polypane, really nice for front-end work, has some very useful tools. Definitely recommend giving it a try.

> I don't think any changes are necessary at this point, it fits the site's theme perfectly

Awesome, I'll clean up my code a little bit and get a PR in!

**Comment by ZS041** [comment]
I added Framer Motion and gave the cards a simple animation on exit and enter using AnimatePresence as a demo. May be going a bit overboard adding additional dependencies, please let me know if so. Can always start a new issue for animations and discuss potential solutions and keep this PR short and sweet with the sort dropdown. I don't want to overstep and implement things that are out of the projects current scope. 

https://user-images.githubusercontent.com/80226316/234648553-e8a8cc17-1d87-453a-ba77-972456143cff.mp4

**Comment by gabrysia694** [comment]
> I added Framer Motion and gave the cards a simple animation on exit and enter using AnimatePresence as a demo. May be going a bit overboard adding additional dependencies, please let me know if so. Can always start a new issue for animations and discuss potential solutions and keep this PR short and sweet with the sort dropdown. I don't want to overstep and implement things that are out of the projects current scope.
> 
>  6f4f30c6b74aa971de77d0d5a2b8aeda.mp4

you didn't go overboard, that's a very nice addition to the site and we'd love to have it! create a PR and I'll be happy to merge it asap :)

**Comment by Bashamega** [comment]
hello:)
Can u assign me?
