### ISSUE TITLE
feat: Implementing a Page Not Found Feature 

### ISSUE THREAD

**Issue by Saurav-Pant** [gabrysia694/Gym-Junkies#91]
To ensure a positive user experience in a React website, it's important to implement a Page Not Found feature that redirects users to a custom error page when they try to access a non-existent page or route. we can use the React Router library to set up a catch-all route and a custom error component that displays a friendly message to users and provides navigation options back to the main site. This is a simple but important step in improving your site's user-friendliness and reducing frustration for your users.
(https://user-images.githubusercontent.com/103263909/234735653-f09facd1-d06e-4239-aab5-5eb9f42c911e.png)
I want to work on it.

**Comment by gabrysia694** [comment]
sounds good, it's all yours then!
