### ISSUE TITLE
Dark mode Enhancement

### ISSUE THREAD

**Issue by haldaranup** [gabrysia694/Gym-Junkies#93]
We should add dark mode effect on cards also(Docs page).

**Comment by gabrysia694** [comment]
> We should add dark mode effect on cards also(Docs page).

Good idea, would you like to work on that?

**Comment by haldaranup** [comment]
> > We should add dark mode effect on cards also(Docs page).
> 
> Good idea, would you like to work on that?

Sure, but some of the gifs we have don't have transparent background, which means they will remain as is, so do we have to change those gifs? Any other solution?

**Comment by gabrysia694** [comment]
If I counted correctly there's 7 gifs with white background so I think we have to replace them. The other solution that came to my mind was adding `filter: invert(1)` to gifs which would get rid of the background problem but gifs themselves would look creepy

**Comment by haldaranup** [comment]
> If I counted correctly there's 7 gifs with white background so I think we have to replace them. The other solution that came to my mind was adding `filter: invert(1)` to gifs which would get rid of the background problem but gifs themselves would look creepy

So, the better solution would be to replace them

**Comment by gabrysia694** [comment]
> > If I counted correctly there's 7 gifs with white background so I think we have to replace them. The other solution that came to my mind was adding `filter: invert(1)` to gifs which would get rid of the background problem but gifs themselves would look creepy
> 
> So, the better solution would be to replace them

yes, seems like the best available solution

**Comment by Shoetan** [comment]
@gabrysia694 I suggest using a free tool like remove bg to remove the backgrounds and retain the quality of the gifs.
