### ISSUE TITLE
Adding unit tests for the existing code

### ISSUE THREAD

**Issue by mshamir11** [gabrysia694/Gym-Junkies#97]
Maintaining a repository and shipping bug free codes is equally important as introducing new features. We need to add automated testing for that.It would then be easy to verify new PRs are not braking any existing features. It would be easy for us to check things manually now. Once things get big, it would be difficult to do manually. We should introduce integration tests and unit tests.

I think, we should start with unit tests first here. It would be good a first issue for beginners to get understand the repo.

**Comment by ydv-ankit** [comment]
hey,
i want to create test cases for this repo, but need help how to do this

**Comment by KNO29** [comment]
Hello,
i would like to create the unit tests, as I already have some experience with testing React applications. If it is ok, I would like to do it.

**Comment by gabrysia694** [comment]
> Hello, i would like to create the unit tests, as I already have some experience with testing React applications. If it is ok, I would like to do it.

ok @KNO29 I'll assign it to you then
